import {useEffect,useState} from 'react';
import type {ChangeEvent} from 'react';
import {SimulationCanvas} from './components/SimulationCanvas';
import {simulate} from './simulation/api';
import type {SimulationConfig,SimulationResult} from './types/models';
import './styles.css';
const scenarios:Record<string,SimulationConfig>={straight_flight:{duration_seconds:20,simulation_timestep_seconds:.1,sensor_interval_seconds:.5,measurement_noise_std:5,random_seed:7,initial_x:0,initial_y:0,initial_speed:10,initial_heading_degrees:0,turn_events:[]},gradual_90_degree_turn:{duration_seconds:20,simulation_timestep_seconds:.1,sensor_interval_seconds:.5,measurement_noise_std:5,random_seed:7,initial_x:0,initial_y:0,initial_speed:10,initial_heading_degrees:0,turn_events:[{start_time_seconds:8,duration_seconds:4,turn_rate_degrees_per_second:22.5}]},s_shaped_path:{duration_seconds:24,simulation_timestep_seconds:.1,sensor_interval_seconds:.5,measurement_noise_std:5,random_seed:7,initial_x:0,initial_y:0,initial_speed:10,initial_heading_degrees:0,turn_events:[{start_time_seconds:6,duration_seconds:3,turn_rate_degrees_per_second:30},{start_time_seconds:13,duration_seconds:6,turn_rate_degrees_per_second:-30}]}};
const defaults=scenarios.straight_flight;
export default function App(){
 const[config,setConfig]=useState(defaults),[result,setResult]=useState<SimulationResult|null>(null),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[error,setError]=useState('');
 const update=(key:keyof SimulationConfig)=>(e:ChangeEvent<HTMLInputElement>)=>setConfig({...config,[key]:Number(e.target.value)});
 useEffect(()=>{if(!playing||!result)return;const id=setInterval(()=>setTime(t=>{const next=t+.05;if(next>=result.configuration.duration_seconds){setPlaying(false);return result.configuration.duration_seconds}return next}),50);return()=>clearInterval(id)},[playing,result]);
 async function run(){setError('');try{setResult(await simulate(config));setTime(0);setPlaying(false)}catch(e){setError(e instanceof Error?e.message:'Unable to run simulation')}}
 return <main><h1>Sensor Tracking Simulator</h1><p className="intro">A hardware-free learning model: one target, constant speed, scheduled turns, and noisy Cartesian position observations.</p><section className="layout"><div className="panel controls"><h2>Run configuration</h2><label>scenario<select value={Object.keys(scenarios).find(name=>scenarios[name]===config)??'custom'} onChange={e=>setConfig({...scenarios[e.target.value]})}>{Object.keys(scenarios).map(name=><option key={name} value={name}>{name.replace(/_/g,' ')}</option>)}</select></label>{(['initial_speed','initial_heading_degrees','measurement_noise_std','sensor_interval_seconds','random_seed'] as const).map(key=><label key={key}>{key.replace(/_/g,' ')}<input type="number" min="0" step="any" value={config[key]} onChange={update(key)}/></label>)}<button onClick={run}>Run simulation</button>{result&&<div className="buttons"><button onClick={()=>setPlaying(!playing)}>{playing?'Pause':'Play'}</button><button onClick={()=>{setTime(0);setPlaying(false)}}>Reset</button></div>}{error&&<p className="error">{error}</p>}</div><div className="panel"><SimulationCanvas result={result} time={time}/>{result&&<p className="time">Simulation time: {time.toFixed(2)}s / {result.configuration.duration_seconds}s</p>}<div className="legend"><span className="truth">● Truth path</span><span className="obs">● Noisy observations</span><span className="estimate">╌ Kalman estimate</span></div></div></section><p className="note">Truth is the actual simulated state; the tracker sees observations only. Heading is measured counterclockwise from positive x; turn rates are signed degrees per second.</p></main>
}
